cc_library(
  name = "err",
  srcs = [
    "err.cc"
  ],
  deps = []
)

cc_library(
  name = "io_aux",
  srcs = [
    "io_aux.cc"
  ],
  deps = []
)

cc_library(
  name = "tcp_server",
  srcs = [
    "tcp_server.cc"
  ],
  deps = []
)

cc_library(
  name = "tcp_client",
  srcs = [
    "tcp_client.cc"
  ],
  deps = []
)
