cc_binary(
  name = "EchoServer",
  srcs = [
    "main.cc"
  ],
  deps = [
    ":echo_server",
    "#gflags",
    "#pthread"
  ]
)


cc_library(
  name = "echo_server",
  srcs = [
    "echo_server.cc"
  ],
  deps = []
)
